name: Bot Request
description: "Ask 4 a Bot"
body:
- type: textarea
  attributes:
    value: "## Welcome"
    label: "A b c"
- type: input
  id: prevalence
  attributes:
    label: Bug prevalence
    description: "How often do you or others encounter this bug?"
    placeholder: "Whenever I visit the user account page (1-2 times a week)"
  validations:
    required: true
